name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/setup-node/issues/27
        node-version: [6.x, 8.x, 10.x, 12.x, 14.x, 16.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Add Git to PATH
        if: runner.os == 'Windows'
        run: |
          echo "C:/Program Files/Git/bin" >> $GITHUB_ENV

      - name: Check Git version and location (Windows only)
        if: runner.os == 'Windows'
        
        run: |
          git --version || echo "Git not found"
          where git || echo "Git location not found"
      - uses: actions/checkout@v4
      - name: install
        run: yarn && (cd packages/bower-json && yarn link) && yarn link bower-json
      - name: lint
        run: npm run lint
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: bower tests
        run: npm test
        env:
          CI: true
      - name: bower-logger tests
        run: (cd packages/bower-logger && npm install && npm test)
        env:
          CI: true
      - name: bower-config tests
        run: (cd packages/bower-config && npm install && npm test)
        env:
          CI: true
      - name: bower-endpoint-parser tests
        run: (cd packages/bower-endpoint-parser && npm install && npm test)
        env:
          CI: true
      - name: bower-json tests
        run: (cd packages/bower-json && npm install && npm test)
        env:
          CI: true
      - name: bower-registry-client tests
        run: (cd packages/bower-registry-client && npm install && npm test)
        env:
          CI: true
